name: CI/CD Pipeline for Node.js and React Application

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Also trigger on PRs to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the specific version of Node.js

      # Step 3: Install Client Dependencies and Build the Client
      - name: Build Client
        run: |
          cd client
          npm install
          npm run build

      # Step 4: Run Linting & Tests for Client (optional but recommended)
      - name: Lint Client
        run: |
          cd client
          npm run lint
          
      - name: Test Client
        run: |
          cd client
          npm test

      # Step 5: Install Server Dependencies and Build the Server
      - name: Install Server Dependencies
        run: |
          cd server
          npm install
          
      - name: Run Server Tests (optional)
        run: |
          cd server
          npm test

      # Step 6: Prepare Deployment Files for the Client and Server
      - name: Prepare Remote Directories
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/game-of-choises/client/dist
            sudo rm -rf /home/ubuntu/game-of-choises/server
            mkdir -p /home/ubuntu/game-of-choises/client
            mkdir -p /home/ubuntu/game-of-choises/server

      # Step 7: Upload Built Client Files to EC2
      - name: Deploy Client Build Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "client/dist/*"
          target: "/home/ubuntu/game-of-choises/client/dist/"

      # Step 8: Upload Server Files to EC2
      - name: Deploy Server Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "server/*, server/package*.json"
          target: "/home/ubuntu/game-of-choises/server/"

      # Step 9: Install Server Dependencies on EC2
      - name: Install Server Dependencies on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/game-of-choises/server
            npm install --production

      # Step 10: Restart PM2 Server Application
      - name: Restart PM2 Application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/game-of-choises
            pm2 reload ecosystem.config.js --only game-of-choises